# Generated by Django 4.0.3 on 2022-03-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
