# Generated by Django 4.0.3 on 2022-03-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_delete_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saying',
            name='pub_date',
        ),
    ]
